/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.List;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Cars;
import model.CarsHistory;

/**
 *
 * @author gyt
 */
public class AddCarsPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddCarsPanel
     */
    CarsHistory history;
    
    
    
    
    public AddCarsPanel(CarsHistory history) {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        lblSerialNum = new javax.swing.JLabel();
        txtSerialNum = new javax.swing.JTextField();
        lblYears = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        lblSeats = new javax.swing.JLabel();
        txtSeats = new javax.swing.JTextField();
        lblManufa = new javax.swing.JLabel();
        txtManuFact = new javax.swing.JTextField();
        lblModelNum = new javax.swing.JLabel();
        txtModelNum = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        rdobtnYes = new javax.swing.JRadioButton();
        rdobtnNo = new javax.swing.JRadioButton();
        lblAvaliable = new javax.swing.JLabel();
        lblMainCert = new javax.swing.JLabel();
        txtMainCert = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        lblSerialNum.setText("Serial Number:");

        lblYears.setText("Year:");

        lblSeats.setText("Seats:");

        lblManufa.setText("Manufacturer:");

        txtManuFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManuFactActionPerformed(evt);
            }
        });

        lblModelNum.setText("Model Number:");

        lblCity.setText("City:");

        group.add(rdobtnYes);
        rdobtnYes.setSelected(true);
        rdobtnYes.setText("yes");

        group.add(rdobtnNo);
        rdobtnNo.setText("no");

        lblAvaliable.setText("Avaliable:");

        lblMainCert.setText("Maintenance certificate:");

        txtMainCert.setText("YYYY-MM-DD");
        txtMainCert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMainCertActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add Cars");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMainCert)
                            .addComponent(lblAvaliable)
                            .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblManufa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblYears, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSerialNum))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMainCert)
                            .addComponent(txtCity)
                            .addComponent(txtModelNum)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdobtnYes)
                                .addGap(59, 59, 59)
                                .addComponent(rdobtnNo)
                                .addGap(0, 68, Short.MAX_VALUE))
                            .addComponent(txtManuFact)
                            .addComponent(txtSeats)
                            .addComponent(txtYear)
                            .addComponent(txtSerialNum)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(btnSave)))
                .addGap(445, 445, 445))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSerialNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSerialNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblYears, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSeats, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSeats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufa)
                    .addComponent(txtManuFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelNum)
                    .addComponent(txtModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdobtnYes)
                    .addComponent(lblAvaliable)
                    .addComponent(rdobtnNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMainCert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMainCert))
                .addGap(52, 52, 52)
                .addComponent(btnSave)
                .addGap(138, 138, 138))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMainCertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMainCertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMainCertActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        ArrayList<Cars> carlist = history.getHistory();
        String serialNum = txtSerialNum.getText();
        if(serialNum.equals(null)){
            JOptionPane.showMessageDialog(this, "The serial number cannot be null.");
                return;
        }
        for(int i = 0;i<carlist.size();i++){
            String s = carlist.get(i).getSerialNum();
            if(serialNum.equals(s)){
                JOptionPane.showMessageDialog(this, "The car already exist.");
                return;
            }
        }
        int year = Integer.parseInt(txtYear.getText());
        int seats = Integer.parseInt(txtSeats.getText());
        if(seats<=0){
            JOptionPane.showMessageDialog(this, "The number of seats must bigger than 0.");
            return;
        }
        
        String manufacturers = txtManuFact.getText();
        String modelNum = txtModelNum.getText();
        String city = txtCity.getText();
        boolean available;
        if(rdobtnNo.isSelected()){
            available = false;
        }else{
            available = true;
        }
        SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
        String sdate = txtMainCert.getText();
        Date date = new Date();
        try {
            date = ft.parse(sdate);
        } catch (ParseException ex) {
            Logger.getLogger(AddCarsPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Please enter the correct date format");
        }
        
        Cars car = history.addNewCar();
        
        car.setAvaliable(available);
        car.setCity(city);
        car.setMainCertificate(date);
        car.setManufacturer(manufacturers);
        car.setModelNum(modelNum);
        car.setSeats(seats);
        car.setSerialNum(serialNum);
        car.setYear(year);
        
       JOptionPane.showMessageDialog(this, "New Car Added.");
       
       txtCity.setText("");
       txtMainCert.setText("YYYY-MM-DD");
       txtManuFact.setText("");
       txtModelNum.setText("");
       txtSeats.setText("");
       txtSerialNum.setText("");
       txtYear.setText("");
       
       
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtManuFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManuFactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManuFactActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup group;
    private javax.swing.JLabel lblAvaliable;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblMainCert;
    private javax.swing.JLabel lblManufa;
    private javax.swing.JLabel lblModelNum;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSerialNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblYears;
    private javax.swing.JRadioButton rdobtnNo;
    private javax.swing.JRadioButton rdobtnYes;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtMainCert;
    private javax.swing.JTextField txtManuFact;
    private javax.swing.JTextField txtModelNum;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSerialNum;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables

}
