/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import java.awt.List;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JPanel;
import model.CarsHistory;

/**
 *
 * @author gyt
 */
public class AdminisPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminisPanel
     */
    CarsHistory history; 
    
    public AdminisPanel(CarsHistory history) {
        initComponents();
        this.history = history;
        ViewCars viewcars = new ViewCars(history);
        jSplitPane1.setTopComponent(viewcars);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAddCars = new javax.swing.JButton();
        btnViewCars = new javax.swing.JButton();

        jSplitPane1.setDividerLocation(630);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel2.setAlignmentX(3.0F);
        jPanel2.setAlignmentY(3.0F);
        jPanel2.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 942, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel2);

        btnAddCars.setText("Add Cars");
        btnAddCars.setFocusable(false);
        btnAddCars.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddCars.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCarsActionPerformed(evt);
            }
        });

        btnViewCars.setText("View Cars");
        btnViewCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCarsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnAddCars)
                .addGap(77, 77, 77)
                .addComponent(btnViewCars)
                .addContainerGap(564, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewCars)
                    .addComponent(btnAddCars))
                .addGap(25, 25, 25))
        );

        jSplitPane1.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCarsActionPerformed
        // TODO add your handling code here:
        AddCarsPanel addCarsPanel = new AddCarsPanel(history);
        jSplitPane1.setTopComponent(addCarsPanel);
    }//GEN-LAST:event_btnAddCarsActionPerformed

    private void btnViewCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCarsActionPerformed
        // TODO add your handling code here:
        ViewCars viewcars = new ViewCars(history);
        jSplitPane1.setTopComponent(viewcars);
    }//GEN-LAST:event_btnViewCarsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCars;
    private javax.swing.JButton btnViewCars;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

}
