/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Person;

/**
 *
 * @author gyt
 */
public class CreatJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatJPanel
     */
    Person person;
    
    public CreatJPanel(Person person) {
        initComponents();
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblGeoData = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        lblTeleNum = new javax.swing.JLabel();
        lblFaxNum = new javax.swing.JLabel();
        lblEmailAdd = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        lblMedRecNum = new javax.swing.JLabel();
        lblHeaPlanBeneNum = new javax.swing.JLabel();
        lblBankAccNum = new javax.swing.JLabel();
        lblCerLicenseNum = new javax.swing.JLabel();
        lblVehicleId = new javax.swing.JLabel();
        lblDeviceId = new javax.swing.JLabel();
        lblLinkedln = new javax.swing.JLabel();
        lblInterProAdd = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGeoData = new javax.swing.JTextField();
        txtDateOfBirth = new javax.swing.JTextField();
        txtTeleNum = new javax.swing.JTextField();
        txtFaxNum = new javax.swing.JTextField();
        txtEmailAdd = new javax.swing.JTextField();
        txtSsn = new javax.swing.JTextField();
        txtMedRecordNum = new javax.swing.JTextField();
        txtHealPlanBeneNum = new javax.swing.JTextField();
        txtBankAccNum = new javax.swing.JTextField();
        txtCertiNum = new javax.swing.JTextField();
        txtVehicleId = new javax.swing.JTextField();
        txtDeviceId = new javax.swing.JTextField();
        txtLinkedln = new javax.swing.JTextField();
        txtInterProAdd = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblPhoto = new javax.swing.JLabel();
        btnPhoto = new javax.swing.JButton();
        lblBioId = new javax.swing.JLabel();
        btnBioId = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Person");

        lblName.setText("Name:");

        lblGeoData.setText("Geographic data:");

        lblDateOfBirth.setText("Data of birth:");

        lblTeleNum.setText("Telephone numbers:");

        lblFaxNum.setText("Fax numbers:");

        lblEmailAdd.setText("Email addresses:");

        lblSsn.setText("SSN:");

        lblMedRecNum.setText("Medical record number:");

        lblHeaPlanBeneNum.setText("Health plan beneficiary number:");

        lblBankAccNum.setText("Bank account numbers:");

        lblCerLicenseNum.setText("Certificate/license number:");

        lblVehicleId.setText("Vehicle identifiers and serial numbers including license plates:");

        lblDeviceId.setText("Device identifiers and serial numbers:");

        lblLinkedln.setText("Linkedln:");

        lblInterProAdd.setText("Internet protocol addresses:");

        lblID.setText("Username:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtDateOfBirth.setText("YYYY-MM-DD");
        txtDateOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateOfBirthActionPerformed(evt);
            }
        });

        txtEmailAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAddActionPerformed(evt);
            }
        });

        txtHealPlanBeneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHealPlanBeneNumActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblPhoto.setText("Full face photos and comparable images");

        btnPhoto.setText("choose photo");
        btnPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhotoActionPerformed(evt);
            }
        });

        lblBioId.setText("Biometric identifiers");

        btnBioId.setText("choose photo");
        btnBioId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBioIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(lblGeoData)
                    .addComponent(lblDateOfBirth)
                    .addComponent(lblTeleNum)
                    .addComponent(lblFaxNum)
                    .addComponent(lblEmailAdd)
                    .addComponent(lblSsn)
                    .addComponent(lblMedRecNum)
                    .addComponent(lblHeaPlanBeneNum)
                    .addComponent(lblBankAccNum)
                    .addComponent(lblCerLicenseNum)
                    .addComponent(lblVehicleId)
                    .addComponent(lblDeviceId)
                    .addComponent(lblLinkedln)
                    .addComponent(lblInterProAdd)
                    .addComponent(lblID)
                    .addComponent(lblPhoto)
                    .addComponent(lblBioId))
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBioId)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMedRecordNum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSsn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailAdd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTeleNum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFaxNum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHealPlanBeneNum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                                    .addComponent(txtGeoData)
                                    .addComponent(txtDateOfBirth))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtBankAccNum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCertiNum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVehicleId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDeviceId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLinkedln, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInterProAdd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPhoto))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblTitle)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeoData)
                    .addComponent(txtGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfBirth)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeleNum)
                    .addComponent(txtTeleNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaxNum)
                    .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailAdd)
                    .addComponent(txtEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSsn)
                    .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedRecNum)
                    .addComponent(txtMedRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeaPlanBeneNum)
                    .addComponent(txtHealPlanBeneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankAccNum)
                    .addComponent(txtBankAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCerLicenseNum)
                    .addComponent(txtCertiNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleId)
                    .addComponent(txtVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeviceId)
                    .addComponent(txtDeviceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedln)
                    .addComponent(txtLinkedln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInterProAdd)
                    .addComponent(txtInterProAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoto)
                    .addComponent(btnPhoto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBioId)
                    .addComponent(btnBioId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtEmailAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddActionPerformed

    private void txtHealPlanBeneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHealPlanBeneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHealPlanBeneNumActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        person.setName(txtName.getText());
        person.setGeographicData(txtGeoData.getText());
        SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
        String sdate = txtDateOfBirth.getText();
        Date date = new Date();
        try {
            date = ft.parse(sdate);
        } catch (ParseException ex) {
            Logger.getLogger(CreatJPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Please enter the correct date format");
        }
        person.setDateOfBrith(date);
        person.setTeleNumbers(txtTeleNum.getText());
        person.setFaxNumbers(txtFaxNum.getText());
        person.setEmailAddresses(txtEmailAdd.getText());
        person.setSsn(txtSsn.getText());
        person.setMedicalRecordNum(txtMedRecordNum.getText());
        person.setHealthPlanBeneNum(txtHealPlanBeneNum.getText());
        person.setBankAccountNum(txtBankAccNum.getText());
        person.setCerificateLicenseNum(txtCertiNum.getText());
        person.setVehicleIdAndSerialNum(txtVehicleId.getText());
        person.setDeviceIdAndSeriaNum(txtDeviceId.getText());
        person.setLinkedln(txtLinkedln.getText());
        person.setInternetProtocalAd(txtInterProAdd.getText());
        person.setID(txtId.getText());
        
        JOptionPane.showMessageDialog(this, "Person infromation saved.");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtDateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfBirthActionPerformed

    private void btnPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhotoActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(true);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("jpg","png");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(btnPhoto);
        if(returnVal == JFileChooser.APPROVE_OPTION){
           File[] arrfiles = chooser.getSelectedFiles();
           if (arrfiles == null || arrfiles.length == 0){
            return;
           }
           File ff = chooser.getSelectedFile();
           String filename = ff.getName();
           String prefix = filename.substring(filename.lastIndexOf(".")+1);
           if(!(prefix.equals("jpg") || prefix.equals("png"))){
               JOptionPane.showMessageDialog(this,"Please choose a picture in .jpg or .png format.");
               return;
           }
           FileInputStream input = null;
           FileOutputStream out = null;
           String path = "C:\\Users\\gyt\\Documents\\NetBeansProjects\\Assignment1\\src\\pic";
           try{
            for (File f : arrfiles){
             File dir = new File(path);
             File[] fs = dir.listFiles();
             HashSet<String> set = new HashSet<String>();
             for (File file : fs){
              set.add(file.getName());
             }
             if (set.contains(f.getName())){
              JOptionPane.showMessageDialog(this,"The file already exists.");
              return;
             }
             String absolutePath = chooser.getSelectedFile().getAbsolutePath();
             ImageIcon photo = new ImageIcon(absolutePath);
             person.setFullFacePhotos(photo);
             input = new FileInputStream(f);
             byte[] buffer = new byte[1024];
             File des = new File(path,f.getName());
             out = new FileOutputStream(des);
             int len = 0;
             while (-1 != (len = input.read(buffer))){
              out.write(buffer,0,len);
             }
             out.close();
             input.close();
            }
           }catch (Exception e1){
            JOptionPane.showMessageDialog(this,"File upload failed");
           }
        
        
        }
    }//GEN-LAST:event_btnPhotoActionPerformed

    private void btnBioIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBioIdActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(true);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("jpg","png");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(btnPhoto);
        if(returnVal == JFileChooser.APPROVE_OPTION){
           File[] arrfiles = chooser.getSelectedFiles();
           if (arrfiles == null || arrfiles.length == 0){
            return;
           }
           File ff = chooser.getSelectedFile();
           String filename = ff.getName();
           String prefix = filename.substring(filename.lastIndexOf(".")+1);
           if(!(prefix.equals("jpg") || prefix.equals("png"))){
               JOptionPane.showMessageDialog(this,"Please choose a picture in .jpg or .png format.");
               return;
           }
           FileInputStream input = null;
           FileOutputStream out = null;
           String path = "C:\\Users\\gyt\\Documents\\NetBeansProjects\\Assignment1\\src\\pic";
           try{
            for (File f : arrfiles){
             File dir = new File(path);
             File[] fs = dir.listFiles();
             HashSet<String> set = new HashSet<String>();
             for (File file : fs){
              set.add(file.getName());
             }
             if (set.contains(f.getName())){
              JOptionPane.showMessageDialog(this,"The file already exists.");
              return;
             }
             String absolutePath = chooser.getSelectedFile().getAbsolutePath();
             ImageIcon bioId = new ImageIcon(absolutePath);
             person.setBiometricId(bioId);
             input = new FileInputStream(f);
             byte[] buffer = new byte[1024];
             File des = new File(path,f.getName());
             out = new FileOutputStream(des);
             int len = 0;
             while (-1 != (len = input.read(buffer))){
              out.write(buffer,0,len);
             }
             out.close();
             input.close();
            }
           }catch (Exception e1){
            JOptionPane.showMessageDialog(this,"File upload failed");
           }
        
        
        }
    }//GEN-LAST:event_btnBioIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBioId;
    private javax.swing.JButton btnPhoto;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblBankAccNum;
    private javax.swing.JLabel lblBioId;
    private javax.swing.JLabel lblCerLicenseNum;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblDeviceId;
    private javax.swing.JLabel lblEmailAdd;
    private javax.swing.JLabel lblFaxNum;
    private javax.swing.JLabel lblGeoData;
    private javax.swing.JLabel lblHeaPlanBeneNum;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblInterProAdd;
    private javax.swing.JLabel lblLinkedln;
    private javax.swing.JLabel lblMedRecNum;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblTeleNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVehicleId;
    private javax.swing.JTextField txtBankAccNum;
    private javax.swing.JTextField txtCertiNum;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtDeviceId;
    private javax.swing.JTextField txtEmailAdd;
    private javax.swing.JTextField txtFaxNum;
    private javax.swing.JTextField txtGeoData;
    private javax.swing.JTextField txtHealPlanBeneNum;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtInterProAdd;
    private javax.swing.JTextField txtLinkedln;
    private javax.swing.JTextField txtMedRecordNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtTeleNum;
    private javax.swing.JTextField txtVehicleId;
    // End of variables declaration//GEN-END:variables
}
