/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.SimpleDateFormat;
import java.util.Date;
import model.Person;

/**
 *
 * @author gyt
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Person person;
    
    public ViewJPanel(Person person) {
        initComponents();
        this.person = person;
        displayPerson();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblGeoData = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        lblTeleNum = new javax.swing.JLabel();
        lblFaxNum = new javax.swing.JLabel();
        lblDeviceId = new javax.swing.JLabel();
        lblEmailAdd = new javax.swing.JLabel();
        txtGeoData = new javax.swing.JTextField();
        lblMedRecNum = new javax.swing.JLabel();
        lblCerLicenseNum = new javax.swing.JLabel();
        txtDateOfBirth = new javax.swing.JTextField();
        lblLinkedln = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblVehicleId = new javax.swing.JLabel();
        lblBankAccNum = new javax.swing.JLabel();
        lblInterProAdd = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblHeaPlanBeneNum = new javax.swing.JLabel();
        txtCertiNum = new javax.swing.JTextField();
        txtLinkedln = new javax.swing.JTextField();
        txtInterProAdd = new javax.swing.JTextField();
        txtDeviceId = new javax.swing.JTextField();
        txtFaxNum = new javax.swing.JTextField();
        txtEmailAdd = new javax.swing.JTextField();
        txtHealPlanBeneNum = new javax.swing.JTextField();
        txtSsn = new javax.swing.JTextField();
        txtTeleNum = new javax.swing.JTextField();
        txtVehicleId = new javax.swing.JTextField();
        txtMedRecordNum = new javax.swing.JTextField();
        txtBankAccNum = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();
        lblShowPhoto = new javax.swing.JLabel();
        lblBioId = new javax.swing.JLabel();
        lblShowBioId = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View Person");

        lblName.setText("Name:");

        lblGeoData.setText("Geographic data:");

        lblDateOfBirth.setText("Data of birth:");

        lblTeleNum.setText("Telephone numbers:");

        lblFaxNum.setText("Fax numbers:");

        lblDeviceId.setText("Device identifiers and serial numbers:");

        lblEmailAdd.setText("Email addresses:");

        lblMedRecNum.setText("Medical record number:");

        lblCerLicenseNum.setText("Certificate/license number:");

        lblLinkedln.setText("Linkedln:");

        lblSsn.setText("SSN:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblVehicleId.setText("Vehicle identifiers and serial numbers including license plates:");

        lblBankAccNum.setText("Bank account numbers:");

        lblInterProAdd.setText("Internet protocol addresses:");

        lblID.setText("Username:");

        lblHeaPlanBeneNum.setText("Health plan beneficiary number:");

        txtEmailAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAddActionPerformed(evt);
            }
        });

        txtHealPlanBeneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHealPlanBeneNumActionPerformed(evt);
            }
        });

        lblPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoto.setText("Full face photos and comparable images");

        lblBioId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBioId.setText("Biometric identifiers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblBioId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGeoData, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDateOfBirth, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTeleNum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFaxNum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmailAdd, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSsn, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedRecNum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeaPlanBeneNum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBankAccNum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCerLicenseNum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVehicleId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDeviceId, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLinkedln, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInterProAdd, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMedRecordNum)
                            .addComponent(txtSsn)
                            .addComponent(txtEmailAdd)
                            .addComponent(txtTeleNum)
                            .addComponent(txtFaxNum)
                            .addComponent(txtHealPlanBeneNum)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                                    .addComponent(txtGeoData)
                                    .addComponent(txtDateOfBirth))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtBankAccNum)
                            .addComponent(txtCertiNum)
                            .addComponent(txtVehicleId)
                            .addComponent(txtDeviceId)
                            .addComponent(txtLinkedln)
                            .addComponent(txtInterProAdd)
                            .addComponent(txtId))
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblShowBioId, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblShowPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblTitle)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeoData)
                    .addComponent(txtGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfBirth)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeleNum)
                    .addComponent(txtTeleNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaxNum)
                    .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailAdd)
                    .addComponent(txtEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSsn)
                    .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedRecNum)
                    .addComponent(txtMedRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeaPlanBeneNum)
                    .addComponent(txtHealPlanBeneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankAccNum)
                    .addComponent(txtBankAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCerLicenseNum)
                    .addComponent(txtCertiNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleId)
                    .addComponent(txtVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeviceId)
                    .addComponent(txtDeviceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedln)
                    .addComponent(txtLinkedln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInterProAdd)
                    .addComponent(txtInterProAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(lblShowPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBioId, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShowBioId, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtEmailAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddActionPerformed

    private void txtHealPlanBeneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHealPlanBeneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHealPlanBeneNumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBankAccNum;
    private javax.swing.JLabel lblBioId;
    private javax.swing.JLabel lblCerLicenseNum;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblDeviceId;
    private javax.swing.JLabel lblEmailAdd;
    private javax.swing.JLabel lblFaxNum;
    private javax.swing.JLabel lblGeoData;
    private javax.swing.JLabel lblHeaPlanBeneNum;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblInterProAdd;
    private javax.swing.JLabel lblLinkedln;
    private javax.swing.JLabel lblMedRecNum;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblShowBioId;
    private javax.swing.JLabel lblShowPhoto;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblTeleNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVehicleId;
    private javax.swing.JTextField txtBankAccNum;
    private javax.swing.JTextField txtCertiNum;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtDeviceId;
    private javax.swing.JTextField txtEmailAdd;
    private javax.swing.JTextField txtFaxNum;
    private javax.swing.JTextField txtGeoData;
    private javax.swing.JTextField txtHealPlanBeneNum;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtInterProAdd;
    private javax.swing.JTextField txtLinkedln;
    private javax.swing.JTextField txtMedRecordNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtTeleNum;
    private javax.swing.JTextField txtVehicleId;
    // End of variables declaration//GEN-END:variables

    private void displayPerson() {
        
        txtName.setText(person.getName());
        txtGeoData.setText(person.getGeographicData());
        SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
        Date date = person.getDateOfBrith();
        txtDateOfBirth.setText(ft.format(date));
        txtTeleNum.setText(person.getTeleNumbers());
        txtFaxNum.setText(person.getFaxNumbers());
        txtEmailAdd.setText(person.getEmailAddresses());
        txtSsn.setText(person.getSsn());
        txtMedRecordNum.setText(person.getMedicalRecordNum());
        txtHealPlanBeneNum.setText(person.getHealthPlanBeneNum());
        txtBankAccNum.setText(person.getBankAccountNum());
        txtCertiNum.setText(person.getCerificateLicenseNum());
        txtVehicleId.setText(person.getVehicleIdAndSerialNum());
        txtDeviceId.setText(person.getDeviceIdAndSeriaNum());
        txtLinkedln.setText(person.getLinkedln());
        txtInterProAdd.setText(person.getInternetProtocalAd());
        txtId.setText(person.getID());
        lblShowPhoto.setIcon(person.getFullFacePhotos());
        lblShowPhoto.getIcon();
        lblShowBioId.setIcon(person.getFullFacePhotos());
        lblShowBioId.getIcon();
        
    }
}
